package com.ginkgocap.ywxt.person.model;

import java.io.Serializable;
import java.util.Date;

/**
 * 权限人脉关联表
 */
public class PersonPermission implements Serializable {

    /**
     * 权限人脉关联id
     */
    private Long id;
    /**
     * 人脉id
     */
    private Long personid;

    /**
     * 类型 1人脉 2用户
     */
    private Short persontype;


    /**
     * 发送人id
     */
    private Long sendid;

    /**
     * 接收人id
     */
    private Long receiveid;

    /**
     * 创建时间
     */
    private Date createtime;

    /**
     * 权限类型
     */
    private Short ptype;

    /**
     * 是否大数据推送
     */
    private Short ispush;

    /**
     * 权限模块
     */
    private String modeltype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_permission.ID
     *
     * @return the value of tb_person_permission.ID
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_permission.ID
     *
     * @param id the value for tb_person_permission.ID
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_permission.personId
     *
     * @return the value of tb_person_permission.personId
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public Long getPersonid() {
        if(null == personid){
            personid = 0L;
        }
        return personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_permission.personId
     *
     * @param personid the value for tb_person_permission.personId
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public void setPersonid(Long personid) {
        this.personid = personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_permission.personType
     *
     * @return the value of tb_person_permission.personType
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public Short getPersontype() {
        if(null == persontype){
            persontype = 0;
        }
        return persontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_permission.personType
     *
     * @param persontype the value for tb_person_permission.personType
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public void setPersontype(Short persontype) {
        this.persontype = persontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_permission.sendId
     *
     * @return the value of tb_person_permission.sendId
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public Long getSendid() {
        if(null == sendid){
            sendid = 0L;
        }
        return sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_permission.sendId
     *
     * @param sendid the value for tb_person_permission.sendId
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public void setSendid(Long sendid) {
        this.sendid = sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_permission.receiveId
     *
     * @return the value of tb_person_permission.receiveId
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public Long getReceiveid() {
        if(null == receiveid){
            receiveid = 0L;
        }
        return receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_permission.receiveId
     *
     * @param receiveid the value for tb_person_permission.receiveId
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public void setReceiveid(Long receiveid) {
        this.receiveid = receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_permission.createtime
     *
     * @return the value of tb_person_permission.createtime
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_permission.createtime
     *
     * @param createtime the value for tb_person_permission.createtime
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_permission.pType
     *
     * @return the value of tb_person_permission.pType
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public Short getPtype() {
        if(null == ptype){
            ptype = 0;
        }
        return ptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_permission.pType
     *
     * @param ptype the value for tb_person_permission.pType
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public void setPtype(Short ptype) {
        this.ptype = ptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_permission.isPush
     *
     * @return the value of tb_person_permission.isPush
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public Short getIspush() {
        if(null == ispush){
            ispush = 0;
        }
        return ispush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_permission.isPush
     *
     * @param ispush the value for tb_person_permission.isPush
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public void setIspush(Short ispush) {
        this.ispush = ispush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_permission.modelType
     *
     * @return the value of tb_person_permission.modelType
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public String getModeltype() {
        if(null == modeltype){
            modeltype = "";
        }
        return modeltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_permission.modelType
     *
     * @param modeltype the value for tb_person_permission.modelType
     * @mbggenerated Mon Mar 16 15:24:09 CST 2015
     */
    public void setModeltype(String modeltype) {
        this.modeltype = modeltype == null ? null : modeltype.trim();
    }
}