package com.ginkgocap.ywxt.person.model;

import java.io.Serializable;
import java.util.Date;

/**
 * 会面
 */
public class PersonMeet implements Serializable {
    /**
     * 会面id
     */
    private Long meetId;

    /**
     * 颜色
     */
    private Short color;
    /**
     * 国家
     */
    private Short country;
    /**
     * 省
     */
    private String province;
    /**
     * 市
     */
    private String city;

    /**
     * 县
     */
    private String town;

    /**
     * 详细地点
     */
    private String location;
    /**
     * 地点横坐标
     */
    private String locX;
    /**
     * 地点纵坐标
     */
    private String locY;
    /**
     * 会面时间
     */
    private Date meetTime;
    /**
     * 重复类型
     */
    private Date repeatType;
    /**
     * 提醒类型
     */
    private Short remindType;
    /**
     * 提醒提前时间
     */
    private Short remindTimes;
    /**
     * 会面附件
     */
    private String taskIdA;
    /**
     * 备注图片视频附件
     */
    private String taskIdV;
    /**
     * 备注其他附件
     */
    private String taskIdO;
    /**
     * 会面附件
     */
    private String taskId;
    /**
     * 创建人
     */
    private Long cid;
    /**
     * 创建时间
     */
    private Date ctime;
    /**
     * 人的ID
     */
    private Long personId;
    /**
     * 人的类型
     */
    private Short personType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.meet_id
     *
     * @return the value of tb_person_meet.meet_id
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public Long getMeetId() {
        if(null == meetId){
            meetId = 0L;
        }
        return meetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.meet_id
     *
     * @param meetId the value for tb_person_meet.meet_id
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setMeetId(Long meetId) {
        this.meetId = meetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.color
     *
     * @return the value of tb_person_meet.color
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public Short getColor() {
        if(null == color){
            color = 0;
        }
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.color
     *
     * @param color the value for tb_person_meet.color
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setColor(Short color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.country
     *
     * @return the value of tb_person_meet.country
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public Short getCountry() {
        if(null == country){
            country = 0;
        }
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.country
     *
     * @param country the value for tb_person_meet.country
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setCountry(Short country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.province
     *
     * @return the value of tb_person_meet.province
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public String getProvince() {
        if(null == province){
            province = "";
        }
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.province
     *
     * @param province the value for tb_person_meet.province
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.city
     *
     * @return the value of tb_person_meet.city
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public String getCity() {
        if(null == city){
            city = "";
        }
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.city
     *
     * @param city the value for tb_person_meet.city
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.town
     *
     * @return the value of tb_person_meet.town
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public String getTown() {
        if(null == town){
            town = "";
        }
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.town
     *
     * @param town the value for tb_person_meet.town
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.location
     *
     * @return the value of tb_person_meet.location
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public String getLocation() {
        if(null == location){
            location = "";
        }
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.location
     *
     * @param location the value for tb_person_meet.location
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.loc_x
     *
     * @return the value of tb_person_meet.loc_x
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public String getLocX() {
        if(null == locX){
            locX = "";
        }
        return locX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.loc_x
     *
     * @param locX the value for tb_person_meet.loc_x
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setLocX(String locX) {
        this.locX = locX == null ? null : locX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.loc_y
     *
     * @return the value of tb_person_meet.loc_y
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public String getLocY() {
        if(null == locY){
            locY = "";
        }
        return locY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.loc_y
     *
     * @param locY the value for tb_person_meet.loc_y
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setLocY(String locY) {
        this.locY = locY == null ? null : locY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.meet_time
     *
     * @return the value of tb_person_meet.meet_time
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public Date getMeetTime() {
        return meetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.meet_time
     *
     * @param meetTime the value for tb_person_meet.meet_time
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setMeetTime(Date meetTime) {
        this.meetTime = meetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.repeat_type
     *
     * @return the value of tb_person_meet.repeat_type
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public Date getRepeatType() {
        return repeatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.repeat_type
     *
     * @param repeatType the value for tb_person_meet.repeat_type
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setRepeatType(Date repeatType) {
        this.repeatType = repeatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.remind_type
     *
     * @return the value of tb_person_meet.remind_type
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public Short getRemindType() {
        return remindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.remind_type
     *
     * @param remindType the value for tb_person_meet.remind_type
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setRemindType(Short remindType) {
        this.remindType = remindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.remind_times
     *
     * @return the value of tb_person_meet.remind_times
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public Short getRemindTimes() {
        return remindTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.remind_times
     *
     * @param remindTimes the value for tb_person_meet.remind_times
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setRemindTimes(Short remindTimes) {
        this.remindTimes = remindTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.task_id_a
     *
     * @return the value of tb_person_meet.task_id_a
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public String getTaskIdA() {
        return taskIdA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.task_id_a
     *
     * @param taskIdA the value for tb_person_meet.task_id_a
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setTaskIdA(String taskIdA) {
        this.taskIdA = taskIdA == null ? null : taskIdA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.task_id_v
     *
     * @return the value of tb_person_meet.task_id_v
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public String getTaskIdV() {
        return taskIdV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.task_id_v
     *
     * @param taskIdV the value for tb_person_meet.task_id_v
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setTaskIdV(String taskIdV) {
        this.taskIdV = taskIdV == null ? null : taskIdV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.task_id_o
     *
     * @return the value of tb_person_meet.task_id_o
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public String getTaskIdO() {
        return taskIdO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.task_id_o
     *
     * @param taskIdO the value for tb_person_meet.task_id_o
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setTaskIdO(String taskIdO) {
        this.taskIdO = taskIdO == null ? null : taskIdO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.task_id
     *
     * @return the value of tb_person_meet.task_id
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.task_id
     *
     * @param taskId the value for tb_person_meet.task_id
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.cid
     *
     * @return the value of tb_person_meet.cid
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.cid
     *
     * @param cid the value for tb_person_meet.cid
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.ctime
     *
     * @return the value of tb_person_meet.ctime
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.ctime
     *
     * @param ctime the value for tb_person_meet.ctime
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.person_id
     *
     * @return the value of tb_person_meet.person_id
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.person_id
     *
     * @param personId the value for tb_person_meet.person_id
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.person_type
     *
     * @return the value of tb_person_meet.person_type
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public Short getPersonType() {
        return personType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.person_type
     *
     * @param personType the value for tb_person_meet.person_type
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setPersonType(Short personType) {
        this.personType = personType;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_meet.content
     *
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_person_meet.note
     *
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.content
     *
     * @return the value of tb_person_meet.content
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.content
     *
     * @param content the value for tb_person_meet.content
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_person_meet.note
     *
     * @return the value of tb_person_meet.note
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_person_meet.note
     *
     * @param note the value for tb_person_meet.note
     * @mbggenerated Mon Mar 16 17:23:52 CST 2015
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}